##                          ##
##         EasyAuth         ##
##     Technical Config     ##
##                          ##

# Hashed global password.
global-password: ${globalPassword}

# Deprecated, left for compatibility
forced-offline-players: ${forcedOfflinePlayers}

# Deprecated, left for compatibility
confirmed-online-players: ${confirmedOnlinePlayers}
